# Generated by Django 5.2.3 on 2025-06-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
